import {
  ElectronicComponent,
  RentalRecord,
  ComponentReservation,
  LabTask,
  LabAuditLog,
  LabUser,
  LabRole,
} from '../types';

export const LAB_USERS: Record<LabRole, LabUser> = {
  hod: {
    id: 'user-hod-01',
    name: 'Dr. G.N Kodandaramaiah',
    email: 'hod.ece@kec.ac.in',
    role: 'hod',
    designation: 'Professor & HoD ECE, R&D Director',
    department: 'Electronics & Communication Engineering',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=250',
  },
  incharge: {
    id: 'user-incharge-01',
    name: 'Dr. M. Lakshmipathy',
    email: 'lakshmipathiece@gmail.com',
    role: 'incharge',
    designation: 'Associate Professor in ECE & Lab Incharge',
    department: 'Electronics & Communication Engineering',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=250',
  },
  instructor: {
    id: 'user-instructor-01',
    name: 'Er. Ramesh Varma',
    email: 'ramesh.varma@kec.ac.in',
    role: 'instructor',
    designation: 'Lab Instructor & Technical Assistant',
    department: 'ECE Component & Hardware Lab',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=250',
  },
  student: {
    id: 'student-demo-01',
    name: 'Ananya Sharma',
    email: 'ananya.ece21@kec.ac.in',
    role: 'student',
    designation: 'B.Tech ECE (Roll: 21ECE045)',
    department: 'Electronics & Communication Engineering',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=250',
  },
};

export const DEFAULT_USERS: LabUser[] = [LAB_USERS.hod, LAB_USERS.incharge, LAB_USERS.instructor];

export const INITIAL_COMPONENTS: ElectronicComponent[] = [
  {
    id: 'comp-esp32-01',
    name: 'ESP32 NodeMCU WiFi & Bluetooth Dev Board',
    modelNumber: 'ESP32-WROOM-32D',
    category: 'Microcontrollers & SoC',
    description: 'Dual-core 240MHz Tensilica LX6, 520KB SRAM, integrated 802.11 b/g/n HT40 Wi-Fi and Bluetooth v4.2 BR/EDR and BLE.',
    specifications: {
      'Operating Voltage': '3.3V',
      'Input Voltage': '5V (USB) or 7-12V (VIN)',
      'Clock Speed': '240 MHz',
      'Flash Memory': '4 MB',
      'GPIO Pins': '36 pins',
    },
    totalQuantity: 35,
    availableQuantity: 24,
    reservedQuantity: 4,
    rentedQuantity: 6,
    inMaintenanceQuantity: 1,
    location: {
      rack: 'Rack A',
      shelf: 'Shelf 2',
      bin: 'Bin 04',
    },
    dailyRentRate: 0, // Free for academic use
    securityDeposit: 250,
    condition: 'Good',
    isHighValueEquipment: false,
    maxRentalDays: 14,
    lastAuditedAt: '2026-09-01',
  },
  {
    id: 'comp-dso-01',
    name: 'Tektronix 50MHz 2-Channel Digital Storage Oscilloscope',
    modelNumber: 'Tektronix TBS1052B-EDU',
    category: 'Test & Measurement',
    description: 'High performance benchtop digital oscilloscope with active courseware support, 1GS/s sample rate, dual-channel, 7-inch WVGA color display.',
    specifications: {
      'Bandwidth': '50 MHz',
      'Channels': '2 Analog Channels',
      'Sample Rate': '1.0 GS/s on each channel',
      'Record Length': '2.5k points at all time bases',
      'Screen': '7 inch Active TFT WVGA (800X480)',
    },
    totalQuantity: 12,
    availableQuantity: 7,
    reservedQuantity: 2,
    rentedQuantity: 2,
    inMaintenanceQuantity: 1,
    location: {
      rack: 'Bench Racks',
      shelf: 'Station Row 1',
      bin: 'Bay 03',
    },
    dailyRentRate: 20,
    securityDeposit: 2000,
    condition: 'Good',
    isHighValueEquipment: true,
    maxRentalDays: 7,
    lastAuditedAt: '2026-09-02',
    serialNumbers: ['TEK-TBS-0912', 'TEK-TBS-0913', 'TEK-TBS-0914', 'TEK-TBS-0915'],
  },
  {
    id: 'comp-rpi4-01',
    name: 'Raspberry Pi 4 Model B (4GB RAM)',
    modelNumber: 'RPI4-MODBP-4GB',
    category: 'Microcontrollers & SoC',
    description: 'Quad core 64-bit ARM Cortex-A72 @ 1.5GHz, dual display support at resolutions up to 4K via a pair of micro-HDMI ports.',
    specifications: {
      'Processor': 'Broadcom BCM2711, Quad core Cortex-A72 1.5GHz',
      'RAM': '4GB LPDDR4-3200 SDRAM',
      'Connectivity': 'Gigabit Ethernet, 2.4/5.0GHz 802.11ac Wi-Fi',
      'Ports': '2x USB 3.0, 2x USB 2.0, 40-pin GPIO',
    },
    totalQuantity: 18,
    availableQuantity: 9,
    reservedQuantity: 3,
    rentedQuantity: 6,
    inMaintenanceQuantity: 0,
    location: {
      rack: 'Rack A',
      shelf: 'Shelf 1',
      bin: 'Bin 02',
    },
    dailyRentRate: 0,
    securityDeposit: 1500,
    condition: 'Good',
    isHighValueEquipment: true,
    maxRentalDays: 14,
    lastAuditedAt: '2026-08-28',
  },
  {
    id: 'comp-funcgen-01',
    name: 'Rigol 25MHz Dual-Channel Arbitrary Function Generator',
    modelNumber: 'Rigol DG1022Z',
    category: 'Test & Measurement',
    description: 'Direct Digital Synthesis (DDS) waveform generator with sine, square, ramp, pulse, noise, and built-in 160 arbitrary waveforms.',
    specifications: {
      'Max Output Frequency': '25 MHz',
      'Channels': '2 Channels',
      'Sample Rate': '200 MSa/s',
      'Vertical Resolution': '14 bits',
      'Waveforms': 'Sine, Square, Ramp, Pulse, Noise, Harmonics, Arb',
    },
    totalQuantity: 8,
    availableQuantity: 5,
    reservedQuantity: 1,
    rentedQuantity: 1,
    inMaintenanceQuantity: 1,
    location: {
      rack: 'Bench Racks',
      shelf: 'Station Row 2',
      bin: 'Bay 01',
    },
    dailyRentRate: 15,
    securityDeposit: 1800,
    condition: 'Needs Calibration',
    isHighValueEquipment: true,
    maxRentalDays: 7,
    lastAuditedAt: '2026-08-30',
  },
  {
    id: 'comp-fluke-01',
    name: 'Fluke 101 Pocket Digital Multimeter with CAT III 600V',
    modelNumber: 'Fluke 101 Basic DMM',
    category: 'Test & Measurement',
    description: 'Compact, lightweight multimeter offering reliable AC/DC voltage measurements, resistance, continuity, and capacitance checks.',
    specifications: {
      'Safety Rating': 'CAT III 600 V',
      'DC Voltage Range': '600.0 V with 0.5% accuracy',
      'AC Voltage Range': '600.0 V (40 Hz to 500 Hz)',
      'Resistance Range': '40.00 MΩ',
      'Capacitance': '100.0 μF',
    },
    totalQuantity: 25,
    availableQuantity: 16,
    reservedQuantity: 2,
    rentedQuantity: 5,
    inMaintenanceQuantity: 2,
    location: {
      rack: 'Rack C',
      shelf: 'Shelf 3',
      bin: 'Bin 11',
    },
    dailyRentRate: 0,
    securityDeposit: 600,
    condition: 'Good',
    isHighValueEquipment: false,
    maxRentalDays: 5,
    lastAuditedAt: '2026-09-04',
  },
  {
    id: 'comp-mpu6050-01',
    name: 'MPU-6050 6-Axis Accelerometer & Gyroscope Sensor Module',
    modelNumber: 'GY-521 MPU6050',
    category: 'Sensors & Modules',
    description: 'Combines a 3-axis gyroscope and a 3-axis accelerometer on the same silicon die together with an onboard Digital Motion Processor (DMP).',
    specifications: {
      'Interface': 'I2C (up to 400kHz)',
      'Supply Voltage': '3.0V - 5.0V (on-board LDO)',
      'Gyro Range': '±250, 500, 1000, 2000 °/s',
      'Accel Range': '±2g, ±4g, ±8g, ±16g',
    },
    totalQuantity: 40,
    availableQuantity: 28,
    reservedQuantity: 3,
    rentedQuantity: 8,
    inMaintenanceQuantity: 1,
    location: {
      rack: 'Rack B',
      shelf: 'Shelf 2',
      bin: 'Bin 15',
    },
    dailyRentRate: 0,
    securityDeposit: 100,
    condition: 'New',
    isHighValueEquipment: false,
    maxRentalDays: 14,
    lastAuditedAt: '2026-09-03',
  },
  {
    id: 'comp-motor-01',
    name: 'L298N Dual H-Bridge Motor Driver Module with Heat Sink',
    modelNumber: 'L298N-MOD',
    category: 'Motors & Actuators',
    description: 'High power dual H-bridge driver chip designed to accept standard TTL logic levels and drive inductive loads such as relays, solenoids, DC and stepping motors.',
    specifications: {
      'Drive Voltage': '5V - 35V',
      'Peak Drive Current': '2A per bridge',
      'Logic Voltage': '5V',
      'Max Power': '25W',
    },
    totalQuantity: 30,
    availableQuantity: 21,
    reservedQuantity: 2,
    rentedQuantity: 6,
    inMaintenanceQuantity: 1,
    location: {
      rack: 'Rack B',
      shelf: 'Shelf 4',
      bin: 'Bin 08',
    },
    dailyRentRate: 0,
    securityDeposit: 150,
    condition: 'Good',
    isHighValueEquipment: false,
    maxRentalDays: 14,
    lastAuditedAt: '2026-09-02',
  },
  {
    id: 'comp-solder-01',
    name: 'Hakko FX-888D Digital Soldering Station (ESD Safe)',
    modelNumber: 'Hakko FX-888D-23BY',
    category: 'Prototyping & Tools',
    description: '70W reliable digital soldering station with selectable preset temperatures and password lockout protection for student lab safety.',
    specifications: {
      'Power Consumption': '70 W',
      'Temperature Range': '50 to 480°C (120 to 899°F)',
      'Temperature Stability': '±1°C (±1.8°F) at idle',
      'ESD Safe': 'Yes, grounded tip',
    },
    totalQuantity: 10,
    availableQuantity: 6,
    reservedQuantity: 1,
    rentedQuantity: 2,
    inMaintenanceQuantity: 1,
    location: {
      rack: 'Soldering Bay',
      shelf: 'Bench 1',
      bin: 'Station S-02',
    },
    dailyRentRate: 10,
    securityDeposit: 1200,
    condition: 'Good',
    isHighValueEquipment: true,
    maxRentalDays: 3,
    lastAuditedAt: '2026-09-05',
  },
  {
    id: 'comp-pwrsupply-01',
    name: 'Korad 30V 5A Adjustable Linear DC Power Supply',
    modelNumber: 'Korad KD3005D',
    category: 'Power & Batteries',
    description: 'Single output adjustable bench DC power supply with digital LED display, coarse & fine voltage/current knobs, overload protection.',
    specifications: {
      'Voltage Range': '0 - 30 V continuously adjustable',
      'Current Range': '0 - 5 A continuously adjustable',
      'Ripple & Noise': '≤ 1mVrms',
      'Display': '4-digit LED display for V & A',
    },
    totalQuantity: 14,
    availableQuantity: 9,
    reservedQuantity: 1,
    rentedQuantity: 3,
    inMaintenanceQuantity: 1,
    location: {
      rack: 'Bench Racks',
      shelf: 'Station Row 3',
      bin: 'Bay 05',
    },
    dailyRentRate: 10,
    securityDeposit: 1500,
    condition: 'Good',
    isHighValueEquipment: true,
    maxRentalDays: 7,
    lastAuditedAt: '2026-09-01',
  },
  {
    id: 'comp-arduino-01',
    name: 'Arduino Uno Rev3 (Original ATmega328P)',
    modelNumber: 'A000066',
    category: 'Microcontrollers & SoC',
    description: 'Classic microcontroller board based on the ATmega328P with 14 digital input/output pins, 6 analog inputs, and 16 MHz ceramic resonator.',
    specifications: {
      'Microcontroller': 'ATmega328P',
      'Operating Voltage': '5V',
      'Input Voltage': '7-12V',
      'Digital I/O Pins': '14 (of which 6 provide PWM output)',
      'Flash Memory': '32 KB (ATmega328P)',
    },
    totalQuantity: 40,
    availableQuantity: 28,
    reservedQuantity: 4,
    rentedQuantity: 7,
    inMaintenanceQuantity: 1,
    location: {
      rack: 'Rack A',
      shelf: 'Shelf 3',
      bin: 'Bin 07',
    },
    dailyRentRate: 0,
    securityDeposit: 200,
    condition: 'Good',
    isHighValueEquipment: false,
    maxRentalDays: 14,
    lastAuditedAt: '2026-09-03',
  },
];

export const INITIAL_RENTALS: RentalRecord[] = [
  {
    id: 'rent-2026-001',
    componentId: 'comp-dso-01',
    componentName: 'Tektronix 50MHz 2-Channel Digital Storage Oscilloscope',
    componentModel: 'Tektronix TBS1052B-EDU',
    quantity: 1,
    studentRollNo: '21ECE045',
    studentName: 'Rohan Deshmukh',
    studentEmail: 'rohan.d21@student.univ.edu',
    studentDepartment: 'ECE',
    studentSemester: 'Semester 7',
    studentPhone: '+91 98451 22301',
    issuedBy: {
      id: 'user-incharge-01',
      name: 'Dr. M. Lakshmipathy',
      role: 'incharge',
    },
    issuedAt: '2026-09-01T10:30:00Z',
    expectedReturnDate: '2026-09-08T17:00:00Z',
    status: 'active',
    conditionOnIssue: 'Good',
    accessoriesIssued: ['2x 100MHz Passive Probes', 'BNC-to-Alligator Cable', 'Power Cord'],
    fineAmount: 0,
    fineStatus: 'none',
    notes: 'Issued for Capstone Hardware Project (Li-Fi Audio Transceiver)',
    gatePassNumber: 'GP-2026-8801',
  },
  {
    id: 'rent-2026-002',
    componentId: 'comp-fluke-01',
    componentName: 'Fluke 101 Pocket Digital Multimeter with CAT III 600V',
    componentModel: 'Fluke 101 Basic DMM',
    quantity: 1,
    studentRollNo: '22ECE012',
    studentName: 'Siddharth Rao',
    studentEmail: 'siddharth.r22@student.univ.edu',
    studentDepartment: 'ECE',
    studentSemester: 'Semester 5',
    studentPhone: '+91 97410 88219',
    issuedBy: {
      id: 'user-instructor-01',
      name: 'Er. Ramesh Varma',
      role: 'instructor',
    },
    issuedAt: '2026-08-25T14:15:00Z',
    expectedReturnDate: '2026-09-02T16:00:00Z', // Past date -> Overdue!
    status: 'overdue',
    conditionOnIssue: 'Good',
    accessoriesIssued: ['TL75 Hard Point Test Lead Set'],
    fineAmount: 50,
    fineStatus: 'pending',
    notes: 'Student notified via automated reminder. Due 5 days ago.',
    gatePassNumber: 'GP-2026-8742',
  },
  {
    id: 'rent-2026-003',
    componentId: 'comp-esp32-01',
    componentName: 'ESP32 NodeMCU WiFi & Bluetooth Dev Board',
    componentModel: 'ESP32-WROOM-32D',
    quantity: 2,
    studentRollNo: '23EEE088',
    studentName: 'Meera Nambiar',
    studentEmail: 'meera.n23@student.univ.edu',
    studentDepartment: 'EEE',
    studentSemester: 'Semester 3',
    studentPhone: '+91 94480 33112',
    issuedBy: {
      id: 'user-instructor-01',
      name: 'Er. Ramesh Varma',
      role: 'instructor',
    },
    issuedAt: '2026-09-04T11:00:00Z',
    expectedReturnDate: '2026-09-18T17:00:00Z',
    status: 'active',
    conditionOnIssue: 'Good',
    accessoriesIssued: ['2x Micro-USB data cables'],
    fineAmount: 0,
    fineStatus: 'none',
    notes: 'Smart Grid metering prototype for IEEE Student branch competition',
    gatePassNumber: 'GP-2026-8819',
  },
  {
    id: 'rent-2026-004',
    componentId: 'comp-rpi4-01',
    componentName: 'Raspberry Pi 4 Model B (4GB RAM)',
    componentModel: 'RPI4-MODBP-4GB',
    quantity: 1,
    studentRollNo: '21CSE104',
    studentName: 'Kunal Sen',
    studentEmail: 'kunal.s21@student.univ.edu',
    studentDepartment: 'CSE',
    studentSemester: 'Semester 7',
    studentPhone: '+91 99002 44102',
    issuedBy: {
      id: 'user-incharge-01',
      name: 'Dr. M. Lakshmipathy',
      role: 'incharge',
    },
    issuedAt: '2026-08-20T09:30:00Z',
    expectedReturnDate: '2026-09-03T16:00:00Z',
    actualReturnDate: '2026-09-03T14:45:00Z',
    status: 'returned',
    conditionOnIssue: 'Good',
    conditionOnReturn: 'Good',
    returnInspectedBy: {
      id: 'user-instructor-01',
      name: 'Er. Ramesh Varma',
      role: 'instructor',
    },
    accessoriesIssued: ['32GB SanDisk MicroSD', 'Type-C Official Power Adapter', 'Micro-HDMI cable'],
    fineAmount: 0,
    fineStatus: 'none',
    notes: 'Returned in pristine condition, SD card formatted and tested.',
    gatePassNumber: 'GP-2026-8699',
  },
];

export const INITIAL_RESERVATIONS: ComponentReservation[] = [
  {
    id: 'resv-2026-101',
    componentId: 'comp-rpi4-01',
    componentName: 'Raspberry Pi 4 Model B (4GB RAM)',
    componentModel: 'RPI4-MODBP-4GB',
    quantity: 2,
    studentRollNo: '22ECE054',
    studentName: 'Aditya Kulkarni',
    studentEmail: 'aditya.k22@student.univ.edu',
    purpose: 'Embedded Computer Vision Lab Exam Preparation',
    labCourseCode: 'EC308 Embedded Systems Lab',
    reservedFrom: '2026-09-10T09:00:00Z',
    reservedUntil: '2026-09-15T17:00:00Z',
    status: 'approved',
    requestedAt: '2026-09-05T11:20:00Z',
    reviewedBy: {
      id: 'user-incharge-01',
      name: 'Dr. M. Lakshmipathy',
      role: 'incharge',
    },
    reviewedAt: '2026-09-05T14:00:00Z',
  },
  {
    id: 'resv-2026-102',
    componentId: 'comp-funcgen-01',
    componentName: 'Rigol 25MHz Dual-Channel Arbitrary Function Generator',
    componentModel: 'Rigol DG1022Z',
    quantity: 1,
    studentRollNo: '23ECE019',
    studentName: 'Sneha Roy',
    studentEmail: 'sneha.r23@student.univ.edu',
    purpose: 'Analog Filter Response plotting for Signals & Systems assignment',
    labCourseCode: 'EC204 Analog Electronics Lab',
    reservedFrom: '2026-09-09T13:00:00Z',
    reservedUntil: '2026-09-11T17:00:00Z',
    status: 'pending',
    requestedAt: '2026-09-07T08:45:00Z',
  },
  {
    id: 'resv-2026-103',
    componentId: 'comp-dso-01',
    componentName: 'Tektronix 50MHz 2-Channel Digital Storage Oscilloscope',
    componentModel: 'Tektronix TBS1052B-EDU',
    quantity: 1,
    studentRollNo: '22EEE033',
    studentName: 'Vikas Bansal',
    studentEmail: 'vikas.b22@student.univ.edu',
    purpose: 'PWM switching waveform analysis of buck-boost converter',
    labCourseCode: 'EE302 Power Electronics Lab',
    reservedFrom: '2026-09-12T10:00:00Z',
    reservedUntil: '2026-09-14T16:00:00Z',
    status: 'pending',
    requestedAt: '2026-09-07T16:15:00Z',
  },
];

export const INITIAL_TASKS: LabTask[] = [
  {
    id: 'task-101',
    title: 'Calibrate DSO probes on Bench 3 & 4 before EC204 Lab',
    description: 'Ensure 10X probe compensation trimmer is adjusted against 1kHz reference square wave signal. Replace worn-out alligator ground clips.',
    category: 'Calibration',
    priority: 'high',
    status: 'todo',
    assignedTo: {
      id: 'user-instructor-01',
      name: 'Er. Ramesh Varma',
      designation: 'Lab Instructor',
    },
    assignedBy: {
      id: 'user-incharge-01',
      name: 'Dr. M. Lakshmipathy',
    },
    dueDate: '2026-09-09',
    createdAt: '2026-09-06T09:00:00Z',
    checklist: [
      { id: 'c1', text: 'Connect probe to 1kHz 5Vpp CAL terminal', completed: true },
      { id: 'c2', text: 'Trim capacitance to flatten square wave edges', completed: false },
      { id: 'c3', text: 'Clean BNC connectors with isopropyl alcohol', completed: false },
      { id: 'c4', text: 'Affix calibration status sticker (Valid Sep 2026)', completed: false },
    ],
    relatedComponentId: 'comp-dso-01',
    relatedComponentName: 'Tektronix 50MHz Oscilloscope',
    benchNotes: 'Bench 3 probe has a loose BNC collar, keep spare probe from Rack C ready.',
  },
  {
    id: 'task-102',
    title: 'Flash MicroPython bootloader & test returned ESP32 batch',
    description: 'Batch of 10 ESP32 boards returned by Semester 6 students. Erase flash, upload latest stable ESP32 MicroPython binary, run Wi-Fi scan test.',
    category: 'Testing & Verification',
    priority: 'medium',
    status: 'in_progress',
    assignedTo: {
      id: 'user-instructor-01',
      name: 'Er. Ramesh Varma',
      designation: 'Lab Instructor',
    },
    assignedBy: {
      id: 'user-incharge-01',
      name: 'Dr. M. Lakshmipathy',
    },
    dueDate: '2026-09-10',
    createdAt: '2026-09-05T14:30:00Z',
    checklist: [
      { id: 'c1', text: 'Verify CP2102 / CH340 USB-UART enumerated on test PC', completed: true },
      { id: 'c2', text: 'Execute esptool.py erase_flash', completed: true },
      { id: 'c3', text: 'Flash esp32-20260811-v1.23.0.bin', completed: true },
      { id: 'c4', text: 'Run test script for GPIO pins and Wi-Fi scan', completed: false },
      { id: 'c5', text: 'Pack tested boards back into antistatic Rack A Bin 04', completed: false },
    ],
    relatedComponentId: 'comp-esp32-01',
    relatedComponentName: 'ESP32 NodeMCU WiFi Dev Board',
  },
  {
    id: 'task-103',
    title: 'Prepare Component Experiment Kits for EC301 Batch A',
    description: 'Prepare 15 kit boxes containing 1x Arduino Uno, 1x Breadboard, 1x MPU6050, 1x L298N driver, jumper bundle, and resistor pack for Monday practicals.',
    category: 'Kit Preparation',
    priority: 'urgent',
    status: 'todo',
    assignedTo: {
      id: 'user-instructor-01',
      name: 'Er. Ramesh Varma',
      designation: 'Lab Instructor',
    },
    assignedBy: {
      id: 'user-incharge-01',
      name: 'Dr. M. Lakshmipathy',
    },
    dueDate: '2026-09-08',
    createdAt: '2026-09-07T10:00:00Z',
    checklist: [
      { id: 'c1', text: 'Assemble 15 plastic organizer trays', completed: true },
      { id: 'c2', text: 'Pick 15x Arduino Uno from Rack A Shelf 3', completed: false },
      { id: 'c3', text: 'Pick 15x MPU6050 & L298N boards from Rack B', completed: false },
      { id: 'c4', text: 'Count and add male-to-male & male-to-female jumper bundles', completed: false },
      { id: 'c5', text: 'Label kits with Batch A Table 1-15 identifiers', completed: false },
    ],
  },
  {
    id: 'task-104',
    title: 'Procurement and restocking audit for discrete passive bins',
    description: 'Quarterly review of 1/4W resistor rolls, 100uF capacitors, 1N4007 diodes, and BC547 transistors in Rack C. Generate purchase requisition if count < 200.',
    category: 'Restocking',
    priority: 'low',
    status: 'under_review',
    assignedTo: {
      id: 'user-incharge-01',
      name: 'Dr. M. Lakshmipathy',
      designation: 'Lab Incharge',
    },
    assignedBy: {
      id: 'user-incharge-01',
      name: 'Dr. M. Lakshmipathy',
    },
    dueDate: '2026-09-15',
    createdAt: '2026-09-02T11:00:00Z',
    checklist: [
      { id: 'c1', text: 'Count 10k, 1k, 220-ohm resistor reels', completed: true },
      { id: 'c2', text: 'Check NE555 and LM358 DIP-8 IC trays', completed: true },
      { id: 'c3', text: 'Draft department purchase requisition document', completed: true },
      { id: 'c4', text: 'Submit to HOD office for signature and sanction', completed: false },
    ],
  },
];

export const INITIAL_LOGS: LabAuditLog[] = [
  {
    id: 'log-001',
    timestamp: '2026-09-07T16:15:00Z',
    action: 'Reservation Submitted',
    performedBy: 'Vikas Bansal (22EEE033)',
    role: 'student',
    details: 'Submitted reservation for Tektronix 50MHz Oscilloscope for 2 days.',
    category: 'reservation',
  },
  {
    id: 'log-002',
    timestamp: '2026-09-07T10:00:00Z',
    action: 'Task Assigned',
    performedBy: 'Dr. M. Lakshmipathy',
    role: 'incharge',
    details: 'Assigned "Prepare Component Experiment Kits for EC301" to Er. Ramesh Varma.',
    category: 'task',
  },
  {
    id: 'log-003',
    timestamp: '2026-09-05T14:00:00Z',
    action: 'Reservation Approved',
    performedBy: 'Dr. M. Lakshmipathy',
    role: 'incharge',
    details: 'Approved reservation for 2x Raspberry Pi 4 Model B for Aditya Kulkarni (22ECE054).',
    category: 'reservation',
  },
  {
    id: 'log-004',
    timestamp: '2026-09-04T11:00:00Z',
    action: 'Component Issued',
    performedBy: 'Er. Ramesh Varma',
    role: 'instructor',
    details: 'Issued 2x ESP32 NodeMCU boards to Meera Nambiar (Gate Pass: GP-2026-8819).',
    category: 'rental',
  },
  {
    id: 'log-005',
    timestamp: '2026-09-03T14:45:00Z',
    action: 'Equipment Returned & Verified',
    performedBy: 'Er. Ramesh Varma',
    role: 'instructor',
    details: 'Verified return of Raspberry Pi 4 from Kunal Sen. Condition: Good.',
    category: 'rental',
  },
];
